#!/usr/bin/env bash
# list-skills.sh — classify every SKILL.md as PRELOAD or on-demand.
#
# The ONLY thing that controls whether a skill is preloaded is whether an agent
# lists it in its `skills:` frontmatter. The SKILL.md file itself carries no
# loading-mode marker, so this script derives the mode from the agents and is the
# authoritative view.
#
#   ./scripts/list-skills.sh             # print the classification table
#   ./scripts/list-skills.sh --annotate  # ALSO write a generated breadcrumb line
#                                         # into each SKILL.md (idempotent, drift-free)
#
# A skill is PRELOAD iff its name appears in some agent's `skills:` list; appears
# in none → on-demand (read only when an agent invokes it via the Skill tool).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Override with SKILLS_AGENTS_DIR to point at a bootstrapped project's agents.
AGENTS_DIR="${SKILLS_AGENTS_DIR:-$ROOT/global-agents}"

ANNOTATE=0
[ "${1:-}" = "--annotate" ] && ANNOTATE=1

# 1. Build "skill -> agents that preload it" from agent frontmatter.
declare -A LOADED_BY
for af in "$AGENTS_DIR"/*.md; do
  [ -f "$af" ] || continue
  agent="$(basename "$af" .md)"
  while IFS= read -r skill; do
    [ -n "$skill" ] || continue
    if [ -n "${LOADED_BY[$skill]:-}" ]; then
      LOADED_BY[$skill]="${LOADED_BY[$skill]}, $agent"
    else
      LOADED_BY[$skill]="$agent"
    fi
  done < <(awk '
    /^skills:[[:space:]]*$/        {inblk=1; next}
    inblk && /^[[:space:]]*-[[:space:]]*/ {sub(/^[[:space:]]*-[[:space:]]*/,""); print; next}
    inblk && /^[^[:space:]]/       {inblk=0}
  ' "$af")
done

# Rewrite one SKILL.md to carry a single generated breadcrumb line, placed right
# after the closing frontmatter `---`. Any prior breadcrumb is stripped first, so
# re-running is idempotent and always reflects the current agent frontmatter.
annotate() {
  local sf="$1" crumb="$2" tmp
  tmp="$(mktemp)"
  awk -v crumb="$crumb" '
    /^<!-- loading:/ { next }            # drop a previous generated crumb
    { buf[++n]=$0 }
    END {
      d=0; end=0
      for (i=1;i<=n;i++) if (buf[i]=="---" && ++d==2) { end=i; break }
      if (end==0) { print crumb }        # no frontmatter: prepend
      for (i=1;i<=n;i++) { print buf[i]; if (i==end) print crumb }
    }
  ' "$sf" > "$tmp" && mv "$tmp" "$sf"
}

# 2. Classify + print (canonical dirs only, so mirrors do not duplicate rows).
printf '%-34s %-11s %s\n' "SKILL" "MODE" "LOADED BY"
printf '%s\n' "----------------------------------------------------------------------"
shopt -s nullglob
for sf in "$ROOT"/global-skills/*/SKILL.md "$ROOT"/global-project-skills/*/SKILL.md; do
  name="$(basename "$(dirname "$sf")")"
  if [ -n "${LOADED_BY[$name]:-}" ]; then
    printf '%-34s %-11s %s\n' "$name" "PRELOAD" "${LOADED_BY[$name]}"
  else
    printf '%-34s %-11s %s\n' "$name" "on-demand" "(invoked via Skill tool when needed)"
  fi
done

# 3. Annotate every canonical copy (global + project skills). There is no .agents/
# mirror any more — it was a vestige of the removed Codex setup and nothing loads it.
if [ "$ANNOTATE" = 1 ]; then
  for sf in "$ROOT"/global-skills/*/SKILL.md \
            "$ROOT"/global-project-skills/*/SKILL.md; do
    name="$(basename "$(dirname "$sf")")"
    if [ -n "${LOADED_BY[$name]:-}" ]; then
      crumb="<!-- loading: PRELOAD by ${LOADED_BY[$name]} — generated by scripts/list-skills.sh --annotate; do not hand-edit (source of truth: agent skills: frontmatter) -->"
    else
      crumb="<!-- loading: on-demand (invoked via the Skill tool when needed) — generated by scripts/list-skills.sh --annotate; do not hand-edit -->"
    fi
    annotate "$sf" "$crumb"
  done
  echo
  echo "[list-skills] annotated breadcrumbs into every canonical SKILL.md."
fi
